// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0w50MXNuAUK1Fd8ZoCCSDNdYGtDnbeGs',
    appId: '1:259082798987:web:dca60a37f2bcd0fccb118e',
    messagingSenderId: '259082798987',
    projectId: 'whats-app-clone-31aa6',
    authDomain: 'whats-app-clone-31aa6.firebaseapp.com',
    storageBucket: 'whats-app-clone-31aa6.appspot.com',
    measurementId: 'G-R6PVZ6H6VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6a0kNwWA8v67YLYLuFAAnuPtMR8o0jNo',
    appId: '1:259082798987:android:d5596fe5a417e67dcb118e',
    messagingSenderId: '259082798987',
    projectId: 'whats-app-clone-31aa6',
    storageBucket: 'whats-app-clone-31aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkcaZ49Nr1tycivL4a196JCm0DgkCvFI',
    appId: '1:259082798987:ios:97c961dd942381cacb118e',
    messagingSenderId: '259082798987',
    projectId: 'whats-app-clone-31aa6',
    storageBucket: 'whats-app-clone-31aa6.appspot.com',
    iosClientId: '259082798987-4vtfdj7d7osmig8uleulfm8beqvvuo4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkcaZ49Nr1tycivL4a196JCm0DgkCvFI',
    appId: '1:259082798987:ios:97c961dd942381cacb118e',
    messagingSenderId: '259082798987',
    projectId: 'whats-app-clone-31aa6',
    storageBucket: 'whats-app-clone-31aa6.appspot.com',
    iosClientId: '259082798987-4vtfdj7d7osmig8uleulfm8beqvvuo4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );
}
